from __future__ import annotations

import argparse
import ast
import json
import re
import subprocess
import sys
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC_DIR = REPO_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from lojban_evolution.control_plane.series_registry import classify_surface_path, known_series, load_script_surface_registry, series_order

DOCS_DIR = REPO_ROOT / "docs"

GENERATED_NOTE = "Generated by `python scripts/control_plane/build_project_cartography.py`. Edit the generator, not this file."


@dataclass
class FileEntry:
    path: str
    kind: str
    bucket: str
    status: str
    family: str
    lines: int
    bytes: int
    purpose: str
    has_main: bool = False
    functions: int = 0
    classes: int = 0
    imports: list[str] | None = None


def _run_git(args: list[str]) -> str:
    result = subprocess.run(["git", *args], cwd=REPO_ROOT, text=True, capture_output=True, check=False)
    if result.returncode != 0:
        return ""
    return result.stdout


def _tracked_files(paths: Iterable[str] | None = None) -> list[Path]:
    args = ["ls-files", "--cached", "--others", "--exclude-standard"]
    if paths:
        args.extend(paths)
    stdout = _run_git(args)
    seen: set[str] = set()
    out: list[Path] = []
    for line in stdout.splitlines():
        item = line.strip()
        if item and item not in seen:
            seen.add(item)
            out.append(REPO_ROOT / item)
    return out


def _rel(path: Path) -> str:
    return path.relative_to(REPO_ROOT).as_posix()


def _safe_read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(encoding="utf-8", errors="replace")


def _line_count(text: str) -> int:
    return len(text.splitlines())


def _first_sentence(text: str, fallback: str = "") -> str:
    text = " ".join(str(text or "").strip().split())
    if not text:
        return fallback
    return text.split(". ")[0].strip(" .")[:160]


def _infer_family(rel: str) -> str:
    classified = classify_surface_path(rel)
    if classified.series != "unclassified":
        return classified.series
    parts = rel.split("/")
    joined = "/".join(parts[:3]).lower()
    for part in parts:
        low = part.lower()
        if re.fullmatch(r"m\d+", low):
            return low.upper()
        if low in {"m_bridge", "control_plane", "data", "training"}:
            return low
    match = re.search(r"(?:^|[_/\-])(m\d+)(?:[_/\-]|$)", joined)
    if match:
        return match.group(1).upper()
    if "j_series" in joined or "/j_" in joined:
        return "J"
    if "l_series" in joined or "/l_" in joined:
        return "L"
    if "h5" in joined:
        return "H5"
    return "shared"


def _bucket_status(path: Path) -> tuple[str, str, str]:
    rel = _rel(path)
    parts = rel.split("/")
    if parts[0] == "scripts":
        if path.suffix.lower() not in {".py", ".ps1"}:
            return "doc", "/".join(parts[:2]) if len(parts) > 1 else "scripts", "local-doc"
        bucket = "/".join(parts[:2]) if len(parts) > 1 else "scripts"
        if len(parts) > 1 and parts[1] == "legacy":
            status = "legacy-runnable"
        elif len(parts) > 1 and parts[1] == "control_plane":
            status = "active-control-plane"
        elif len(parts) > 1 and parts[1] in {"data", "training"}:
            status = "active-shared-utility"
        else:
            status = "active-family-runner"
        return "script", bucket, status
    if parts[:2] == ["airflow", "dags"]:
        if path.suffix.lower() != ".py":
            return "doc", "/".join(parts[:2]), "local-doc"
        bucket = "/".join(parts[:3]) if len(parts) > 2 else "airflow/dags"
        status = "legacy-dag" if "legacy" in parts else "active-dag"
        return "dag", bucket, status
    if parts[0] == "src":
        bucket = "/".join(parts[:3]) if len(parts) > 2 else "src"
        return "library", bucket, "active-library"
    if parts[0] == "tests":
        return "test", "tests", "active-test"
    if parts[0] == "docs":
        return "doc", "/".join(parts[:2]) if len(parts) > 1 else "docs", "human-doc"
    if parts[0] in {"configs", "config"}:
        return "config", parts[0], "configuration"
    return "other", parts[0], "tracked"


def _python_meta(path: Path, text: str) -> dict[str, Any]:
    meta: dict[str, Any] = {
        "purpose": "",
        "has_main": False,
        "functions": 0,
        "classes": 0,
        "imports": [],
    }
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return meta
    doc = ast.get_docstring(tree)
    if doc:
        meta["purpose"] = _first_sentence(doc)
    imports: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            meta["functions"] += 1
        elif isinstance(node, ast.ClassDef):
            meta["classes"] += 1
        elif isinstance(node, ast.Import):
            for alias in node.names:
                imports.add(alias.name.split(".")[0])
        elif isinstance(node, ast.ImportFrom) and node.module:
            imports.add(node.module.split(".")[0])
        elif isinstance(node, ast.If):
            test = ast.dump(node.test)
            if "__main__" in test:
                meta["has_main"] = True
        elif isinstance(node, ast.Call):
            func_name = ""
            if isinstance(node.func, ast.Attribute):
                func_name = node.func.attr
            elif isinstance(node.func, ast.Name):
                func_name = node.func.id
            if func_name == "ArgumentParser":
                for kw in node.keywords:
                    if kw.arg == "description" and isinstance(kw.value, ast.Constant) and isinstance(kw.value.value, str):
                        meta["purpose"] = _first_sentence(kw.value.value, meta["purpose"])
    meta["imports"] = sorted(imports)[:12]
    return meta


def _purpose_from_name(path: Path) -> str:
    stem = path.stem.replace("_", " ").replace("-", " ")
    return stem[:1].upper() + stem[1:]


def build_entries() -> list[FileEntry]:
    paths = _tracked_files(["scripts", "airflow/dags", "src", "tests", "docs", "configs", "config"])
    entries: list[FileEntry] = []
    for path in paths:
        if not path.is_file():
            continue
        rel = _rel(path)
        if "__pycache__" in rel or rel.endswith(".pyc"):
            continue
        kind, bucket, status = _bucket_status(path)
        if kind not in {"script", "dag", "library", "test", "doc", "config"}:
            continue
        text = _safe_read(path)
        meta = _python_meta(path, text) if path.suffix == ".py" else {}
        purpose = str(meta.get("purpose") or "") if meta else ""
        if not purpose:
            purpose = _purpose_from_name(path)
        entries.append(
            FileEntry(
                path=rel,
                kind=kind,
                bucket=bucket,
                status=status,
                family=_infer_family(rel),
                lines=_line_count(text),
                bytes=path.stat().st_size,
                purpose=purpose,
                has_main=bool(meta.get("has_main", False)) if meta else path.suffix.lower() in {".ps1"},
                functions=int(meta.get("functions", 0)) if meta else 0,
                classes=int(meta.get("classes", 0)) if meta else 0,
                imports=list(meta.get("imports", [])) if meta else [],
            )
        )
    return sorted(entries, key=lambda item: item.path)


def _markdown_table(headers: list[str], rows: list[list[Any]]) -> str:
    out = ["| " + " | ".join(headers) + " |", "| " + " | ".join(["---"] * len(headers)) + " |"]
    for row in rows:
        cells = []
        for value in row:
            text = str(value).replace("\n", " ").replace("|", "\\|")
            cells.append(text)
        out.append("| " + " | ".join(cells) + " |")
    return "\n".join(out)


def _redundancy(entries: list[FileEntry]) -> dict[str, Any]:
    active_scripts = [e for e in entries if e.kind in {"script", "dag"}]
    by_bucket = defaultdict(list)
    for e in active_scripts:
        by_bucket[e.bucket].append(e)
    large = sorted([e for e in entries if e.lines >= 500], key=lambda e: e.lines, reverse=True)[:30]
    legacy = [e for e in active_scripts if "legacy" in e.status]
    family_runner_count = Counter(e.family for e in active_scripts if e.status == "active-family-runner")
    dag_family_count = Counter(e.family for e in active_scripts if e.kind == "dag")

    stem_groups: dict[str, list[FileEntry]] = defaultdict(list)
    for e in active_scripts:
        stem = Path(e.path).stem.lower()
        norm = re.sub(r"^(run|train|eval|build|render|summarize)_", "", stem)
        norm = re.sub(r"_dag$", "", norm)
        stem_groups[norm].append(e)
    similar_stems = {
        key: sorted([e.path for e in values])
        for key, values in stem_groups.items()
        if len(values) > 1
    }

    tracked_baselines = [e.path for e in entries if e.path.startswith("docs/baselines/test_m_series_baseline_")]
    archive_exports = [p for p in _tracked_files(["archive/exports"]) if p.is_file()]
    active_names = {Path(e.path).name for e in active_scripts}
    mirrored_exports = []
    for path in archive_exports:
        name = path.name
        if name.endswith(".txt"):
            possible = name[:-4]
            if possible in active_names:
                mirrored_exports.append(_rel(path))

    return {
        "large_files": [asdict(e) for e in large],
        "legacy_script_count": len(legacy),
        "legacy_script_lines": sum(e.lines for e in legacy),
        "family_runner_count": dict(sorted(family_runner_count.items())),
        "dag_family_count": dict(sorted(dag_family_count.items())),
        "similar_stem_clusters": similar_stems,
        "tracked_test_baselines": tracked_baselines,
        "mirrored_archive_exports_sample": mirrored_exports[:40],
        "mirrored_archive_exports_count": len(mirrored_exports),
        "bucket_counts": {bucket: len(values) for bucket, values in sorted(by_bucket.items())},
    }



def _write_root_index_stub(generated_at: str) -> None:
    text = f"""# Project Index

{GENERATED_NOTE}

Generated: `{generated_at}`

Use [docs/PROJECT_INDEX.md](docs/PROJECT_INDEX.md) as the operational front door for this repo.

That document points to:

- [docs/SCRIPT_INVENTORY.md](docs/SCRIPT_INVENTORY.md) for every tracked runnable script/DAG surface.
- [docs/REDUNDANCY_AUDIT.md](docs/REDUNDANCY_AUDIT.md) for likely duplicate or stale code zones.
- [docs/DEPRECATION_LEDGER.md](docs/DEPRECATION_LEDGER.md) for safe-delete/replacement status.
- [docs/SCAFFOLDING_PLAYBOOK.md](docs/SCAFFOLDING_PLAYBOOK.md) for rules on adding new ablation families and scripts.
- [docs/project_cartography_manifest.json](docs/project_cartography_manifest.json) for the machine-readable inventory.

`README.md` is still useful historical context, but this file is the current navigation entrypoint.

Regenerate with:

```powershell
python scripts/control_plane/build_project_cartography.py
```
"""
    (REPO_ROOT / "PROJECT_INDEX.md").write_text(text, encoding="utf-8")


def _write_project_index(entries: list[FileEntry], redundancy: dict[str, Any], generated_at: str) -> None:
    counts = Counter(e.kind for e in entries)
    status_counts = Counter(e.status for e in entries)
    lines_by_kind = Counter()
    for e in entries:
        lines_by_kind[e.kind] += e.lines
    text = f"""# Project Index

{GENERATED_NOTE}

Generated: `{generated_at}`

This is the front-door map for `D:/lojbanhypop`. It complements the lineage ledger by answering the operational question: where do I go, what is active, and what is likely redundant?

## Source Of Truth

- Human series map: [docs/SERIES_FIELD_GUIDE.md](SERIES_FIELD_GUIDE.md)
- Canonical history: [docs/ABLATION_HISTORY_FULL.md](ABLATION_HISTORY_FULL.md)
- Program spine: [docs/ABLATION_PROGRAM_SPINE.md](ABLATION_PROGRAM_SPINE.md)
- Program map: [docs/ABLATION_PROGRAM_MAP.md](ABLATION_PROGRAM_MAP.md)
- Layout policy: [docs/REPO_LAYOUT.md](REPO_LAYOUT.md)
- Script inventory: [docs/SCRIPT_INVENTORY.md](SCRIPT_INVENTORY.md)
- Redundancy audit: [docs/REDUNDANCY_AUDIT.md](REDUNDANCY_AUDIT.md)
- Deprecation ledger: [docs/DEPRECATION_LEDGER.md](DEPRECATION_LEDGER.md)
- Future scaffolding playbook: [docs/SCAFFOLDING_PLAYBOOK.md](SCAFFOLDING_PLAYBOOK.md)
- Machine manifest: [docs/project_cartography_manifest.json](project_cartography_manifest.json)

## Current Shape

{_markdown_table(["Kind", "Tracked files", "Tracked lines"], [[kind, counts[kind], lines_by_kind[kind]] for kind in sorted(counts)])}

## Status Buckets

{_markdown_table(["Status", "Files"], [[status, status_counts[status]] for status in sorted(status_counts)])}

## Series Buckets

{_markdown_table(["Series", "Files"], [[series, Counter(e.family for e in entries)[series]] for series in series_order() if Counter(e.family for e in entries)[series] > 0])}

## Practical Reading Order

1. Start with `docs/PROJECT_INDEX.md` for navigation.
2. Use `docs/SCRIPT_INVENTORY.md` before running or editing any script.
3. Use `docs/REDUNDANCY_AUDIT.md` before deleting, moving, or merging anything.
4. Use `docs/SCAFFOLDING_PLAYBOOK.md` when adding a new ablation family or runner.
5. Regenerate this layer with `python scripts/control_plane/build_project_cartography.py` after adding scripts, DAGs, or docs.

## Main Architectural Warning

The repo has a good ledger, but it also has real historical sediment: legacy scripts, mirrored NotebookLM exports, repeated runner/DAG boilerplate, and large control-plane monoliths. The safe cleanup strategy is not mass deletion. It is classification first, then quarantine, then replacement behind tests.

"""
    (DOCS_DIR / "PROJECT_INDEX.md").write_text(text, encoding="utf-8")


def _write_script_inventory(entries: list[FileEntry], generated_at: str) -> None:
    script_entries = [e for e in entries if e.kind in {"script", "dag"}]
    rows = []
    for e in script_entries:
        rows.append([e.path, e.bucket, e.status, e.family, e.lines, "yes" if e.has_main else "no", e.purpose])
    by_bucket = Counter(e.bucket for e in script_entries)
    text = f"""# Script Inventory

{GENERATED_NOTE}

Generated: `{generated_at}`

Scope: tracked runnable surfaces under `scripts/` and `airflow/dags/`. Archive text exports are excluded from the table because they are preserved evidence, not active command surfaces.

## Bucket Counts

{_markdown_table(["Bucket", "Runnable files"], [[bucket, by_bucket[bucket]] for bucket in sorted(by_bucket)])}

## Inventory

{_markdown_table(["Path", "Bucket", "Status", "Family", "Lines", "CLI", "Purpose"], rows)}

"""
    (DOCS_DIR / "SCRIPT_INVENTORY.md").write_text(text, encoding="utf-8")


def _write_redundancy(entries: list[FileEntry], redundancy: dict[str, Any], generated_at: str) -> None:
    large_rows = [[item["path"], item["kind"], item["status"], item["lines"], item["purpose"]] for item in redundancy["large_files"][:20]]
    family_rows = [[family, count] for family, count in redundancy["family_runner_count"].items()]
    dag_rows = [[family, count] for family, count in redundancy["dag_family_count"].items()]
    baseline_rows = [[path] for path in redundancy["tracked_test_baselines"]]
    similar_rows = []
    for key, paths in sorted(redundancy["similar_stem_clusters"].items()):
        if len(similar_rows) >= 40:
            break
        similar_rows.append([key, "<br>".join(paths)])

    text = f"""# Redundancy Audit

{GENERATED_NOTE}

Generated: `{generated_at}`

This is a map of likely redundancy, not a deletion order. Anything listed here needs a preserving move, replacement test, or lineage note before removal.

## Headline Findings

- Legacy runnable surface: `{redundancy['legacy_script_count']}` tracked legacy scripts/DAGs, about `{redundancy['legacy_script_lines']}` lines.
- Mirrored archive exports matching active script names: `{redundancy['mirrored_archive_exports_count']}` sampled from `archive/exports/`.
- Tracked generated test baselines: `{len(redundancy['tracked_test_baselines'])}` files matching `docs/baselines/test_m_series_baseline_*`.
- Large-file pressure is concentrated in control-plane renderers/backfills, legacy runners, shared trainers, and a few major family scripts.

## Large Files To Split Or Quarantine First

{_markdown_table(["Path", "Kind", "Status", "Lines", "Purpose"], large_rows)}

## Active Family Runner Density

{_markdown_table(["Family", "Active runner scripts"], family_rows)}

## DAG Density

{_markdown_table(["Family", "DAG files"], dag_rows)}

## Similar Stem Clusters

These are not automatically duplicates. Many are intentional script-plus-DAG pairs. They are still useful as cleanup targets because they identify repeated wrapper logic and boilerplate.

{_markdown_table(["Normalized stem", "Paths"], similar_rows)}

## Tracked Generated Baseline Candidates

{_markdown_table(["Path"], baseline_rows) if baseline_rows else "No tracked generated baseline candidates found."}

## Cleanup Doctrine

1. Do not mass-delete legacy scripts. Move or deprecate only after the inventory says what replaces them.
2. Replace repeated Airflow boilerplate with family-level DAG factories before removing individual DAGs.
3. Split control-plane monoliths only behind golden output tests.
4. Treat `archive/exports/` as evidence, not runtime. It can be compressed or moved, but not silently deleted.
5. Generated one-off baselines should have either a stable manifest owner or be ignored/scrubbed by test cleanup.

## Highest-Value Refactor Targets

1. `scripts/control_plane/run_ablation_history_backfill.py`: very large control-plane monolith; split registry loading, normalization, rendering, and IO.
2. `scripts/control_plane/run_whole_ablation_grid.py`: high-value but overloaded; split metric extraction from report rendering.
3. Airflow family DAGs: repeated argument plumbing; introduce a shared family DAG factory.
4. `scripts/legacy/`: keep as runnable archaeology, but add replacement pointers per file.
5. Family suite wrappers (`scripts/m19`, `scripts/m20`, `scripts/m21`): extract shared suite/audit report mechanics.

"""
    (DOCS_DIR / "REDUNDANCY_AUDIT.md").write_text(text, encoding="utf-8")


def _write_deprecation_ledger(entries: list[FileEntry], generated_at: str) -> None:
    registry = load_script_surface_registry()
    rows = []
    for entry in entries:
        if entry.status not in {"legacy-runnable", "legacy-dag"}:
            continue
        classified = classify_surface_path(entry.path, registry)
        rows.append(
            [
                entry.path,
                classified.series if classified.series != "unclassified" else entry.family,
                entry.status,
                classified.replacement or "No direct replacement recorded yet.",
                classified.note or "Preserved for historical reproduction; do not extend without a replacement plan.",
            ]
        )
    text = f"""# Deprecation Ledger

{GENERATED_NOTE}

Generated: `{generated_at}`

This ledger is the safe-deletion gate for historical runnable surfaces. A legacy script can only be removed after this file names its replacement, reproduction value, and deletion/move decision.

## Legacy Runnable Surfaces

{_markdown_table(["Path", "Series", "Status", "Replacement", "Note"], rows)}

## Rules

1. Do not delete a legacy script with `No direct replacement recorded yet.`
2. Prefer adding a deprecation header before moving a script.
3. Keep legacy aliases as aliases; future physical layout should use `scripts/m<N>/`, `scripts/control_plane/`, `scripts/data/`, or `scripts/training/`.
4. If a legacy script is preserved only as evidence, move it under `archive/` with a manifest entry rather than leaving it as an active runnable surface.

"""
    (DOCS_DIR / "DEPRECATION_LEDGER.md").write_text(text, encoding="utf-8")


def _write_playbook(generated_at: str) -> None:
    text = f"""# Scaffolding Playbook

{GENERATED_NOTE}

Generated: `{generated_at}`

This file defines how future work should be added so the repo does not grow another hidden maze.

## New Ablation Family Checklist

1. Add reusable code under `src/lojban_evolution/<family>/`.
2. Add runnable CLIs under `scripts/<family>/`.
3. Add Airflow orchestration under `airflow/dags/<family>/` only if it is a repeated workflow.
4. Register the family in the relevant `family.py`, taxonomy, direct unified eval, and whole-grid surfaces.
5. Add tests for generator/data contracts, CLI smoke, direct eval, and whole-grid metric projection.
6. Run `python scripts/control_plane/build_project_cartography.py` and inspect `docs/SCRIPT_INVENTORY.md` before committing.
7. Keep strict accuracy canonical; mark phrase/soft metrics diagnostic unless the contract explicitly says otherwise.

## New Script Rules

- A script must have an `argparse.ArgumentParser(description=...)` description.
- A script must write under an approved output root (`artifacts/`, `archive/`, or a documented legacy `runs/` contract).
- A script should call reusable library code from `src/` rather than hiding experiment logic in a CLI wrapper.
- A script should not duplicate report rendering if a control-plane helper already exists.
- If a script is one-off archaeology, put it in `scripts/legacy/` and state its replacement surface.

## Deprecation Template

When replacing an old script, add this note near the top before moving/deleting:

```python
# Deprecated: superseded by scripts/<family>/<new_runner>.py.
# Kept for historical reproduction of <artifact/run/document>.
```

Then update `docs/SCRIPT_INVENTORY.md` by regenerating cartography.

## Future Scaffolding Files

- `docs/PROJECT_INDEX.md`: front-door map.
- `docs/SCRIPT_INVENTORY.md`: generated list of runnable surfaces.
- `docs/REDUNDANCY_AUDIT.md`: generated cleanup map.
- `docs/DEPRECATION_LEDGER.md`: generated legacy replacement ledger.
- `docs/project_cartography_manifest.json`: machine-readable index.
- `docs/SCAFFOLDING_PLAYBOOK.md`: this policy file.

## Guardrail

If an experiment cannot be placed in exactly one family bucket and one ledger contract, the design is not ready to code. That little rule is boring. It will save us from the hydra.

"""
    (DOCS_DIR / "SCAFFOLDING_PLAYBOOK.md").write_text(text, encoding="utf-8")


def _write_manifest(entries: list[FileEntry], redundancy: dict[str, Any], generated_at: str) -> None:
    payload = {
        "generated_at": generated_at,
        "repo_root": str(REPO_ROOT),
        "series_order": series_order(),
        "known_series": sorted(known_series()),
        "summary": {
            "tracked_inventory_files": len(entries),
            "runnable_surfaces": sum(1 for e in entries if e.kind in {"script", "dag"}),
            "library_files": sum(1 for e in entries if e.kind == "library"),
            "test_files": sum(1 for e in entries if e.kind == "test"),
            "doc_files": sum(1 for e in entries if e.kind == "doc"),
            "config_files": sum(1 for e in entries if e.kind == "config"),
        },
        "series_counts": dict(sorted(Counter(e.family for e in entries).items())),
        "entries": [asdict(e) for e in entries],
        "redundancy": redundancy,
    }
    (DOCS_DIR / "project_cartography_manifest.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Build project cartography docs: script inventory, redundancy audit, and future scaffolding map.")
    parser.add_argument("--check", action="store_true", help="Build in memory and print summary without writing files.")
    args = parser.parse_args(argv)
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    entries = build_entries()
    redundancy = _redundancy(entries)
    if args.check:
        print(json.dumps({"entries": len(entries), "runnable": sum(1 for e in entries if e.kind in {"script", "dag"})}, indent=2))
        return
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    _write_root_index_stub(generated_at)
    _write_project_index(entries, redundancy, generated_at)
    _write_script_inventory(entries, generated_at)
    _write_redundancy(entries, redundancy, generated_at)
    _write_deprecation_ledger(entries, generated_at)
    _write_playbook(generated_at)
    _write_manifest(entries, redundancy, generated_at)
    print(f"Wrote project cartography docs under {DOCS_DIR}")
    print(f"Tracked inventory entries: {len(entries)}")
    print(f"Runnable surfaces: {sum(1 for e in entries if e.kind in {'script', 'dag'})}")


if __name__ == "__main__":
    main()
